# Verification/Estimation Parameters
cliente: "Generic"
estim_year: 2025
estim_month: 6
issue_year: 2025
issue_month: 6

# Operation type: 'verif' or 'stim'
operation: "verif"

# Control flags
update_contract_data: true
api_call: false
ssaa_dn: false
